version: '3'
services:
    producer:
        build: ./consumer/
        networks:
            - consumer-producer
        ports:
            - '8080:8080'
    consumer:
        build: ./producer/
        networks:
            - consumer-producer
        ports:
            - '8800:8080'
        depends_on:
            - producer
networks:
    consumer-producer:
